"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
$hostname\
[ ](bg:surface0)\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$terraform\
$singularity$kubernetes$vcsh$hg_branch$pijul_channel$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$solidity$swift$vlang$vagrant$zig$buf$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$cpp$kotlin$ocaml$pixi$rlang$php$crystal$custom$status\
[](fg:teal bg:blue)\
$docker_context\
[](fg:blue bg:lavender)\
$time\
[ ](fg:lavender)\
$line_break$character"""


palette = 'catppuccin_macchiato'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user]($style)'

[hostname]
format = "[@$hostname]($style)"
style = "bg:surface0 fg:text"


[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "" 

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

#region tools
[nodejs]
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = "" #" "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = " " #" "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = "" #" "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[terraform]
symbol = "󱁢"
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[crystal]
symbol = " "
style = "bg:teal"
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"

[deno]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
version_format = "${raw}"

[lua]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "⨀ "
version_format = "${raw}"

[ruby]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "
version_format = "${raw}"

[swift]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "
version_format = "${raw}"

[aws]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[buf]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "■ "

[cpp]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[ocaml]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[perl]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "


[pixi]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "pixi "

[rlang]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[meson]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "meson "

[conda]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "◯ "

[dart]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "


[elixir]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[elm]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "◩ "

[julia]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "◎ "

[memory_usage]
format = " mem [${ram}( ${swap})]($style)"
style = "bg:teal"
symbol = "▪▫▪ "

[nim]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "▴▲▴ "

[nix_shell]
format = '[$symbol nix⎪$state⎪]($style) [$name]($style)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
style = "fg:base bg:teal"
symbol = ' '
unknown_msg = '[◌](bold dimmed ellow)'

[spack]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "◇ "

[zig]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[scala]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[singularity]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "singularity "

[kubernetes]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[vcsh]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "vcsh "

[cobol]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "cobol "

[daml]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "daml "

[dotnet]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = ".NET "

[erlang]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[fennel]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[haxe]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[helm]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "helm "

[opa]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "opa "

[pulumi]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "pulumi "

[purescript]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[raku]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "raku "

[red]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "red "

[solidity]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[vlang]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "vlang "

[vagrant]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "vagrant "

[gcloud]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "gcloud "

[openstack]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = "openstack "

[azure]
format = "[[ $symbol( $version) ](fg:base bg:teal)]($style)"
style = "bg:teal"
symbol = " "

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

#endregion tools

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:lavender)'
vimcmd_replace_symbol = '[](bold fg:lavender)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
