[tools]
neovim = "0.11.1"
eza = "0.21.3"
fzf = "0.62.0"
python = "3.13.3"
ripgrep = "14.1.1"
yq = "4.45.4"
zoxide = "latest"
starship = "1.23.0"
bat = "0.25.0"
fd = "10.2.0"
terraform = "1.12.0"
ansible = "11.6.0"
packer = "1.12.0"
lazygit = "0.50.0"
gdu = "5.30.1"
bottom = "0.10.2"
pipx = "1.7.1"

[settings]
trusted_config_paths = [
    '~/',
    '~/dotfiles/ '
]
