[tools]
neovim = "0.11.0"
eza = "0.21.0"
fzf = "0.61.1"
python = "3.13.3"
ripgrep = "14.1.1"
yq = "4.45.1"
zoxide = "0.9.7"
starship = "1.22.1"
bat = "0.25.0"
fd = "10.2.0"
terraform = "1.11.4"
ansible = "11.4.0"
packer = "1.12.0"
